# list of primary rules
rules:
- valueFor: '*Type*' # If user specifies "*Type*: Question" above, it will get labeled with "question" and "plz help"
  contains: Question
  addLabels: ['question', 'plz help']
- valueFor: '*Type*'
  contains: Bug
  addLabels: ['bug']
- valueFor: '*Type*'
  contains: Feature
  addLabels: ['enhancement']
- valueFor: '**Assign to damccorm**' # If user specifies "**Assign to damccorm**: yes", it will get labeled with "damccorms problem now" and assigned to "@damccorm"
  contains: yes
  addLabels: ['damccorms problem now']
  assign: ['damccorm']

# List of secondary rules to run if no matches detected in primary rules
nomatches:
- contains: 'this should get assigned to damccorm' # Checks the entire issue for a substring match. If one is found, adds labels "damccorms problem now" and "maybe?", and assigns to "@damccorm"
  addLabels: ['damccorms problem now', 'maybe?']
  assign: ['damccorm']

# List that always runs after rules and nomatches. Look for missing sets of tags here.
tags:
- noneIn: ['bug', 'enhancement', 'question'] # If no bug, enhancement, or question labels are added, label with 'triage'
  addLabels: ['triage']
